Presentation/Nop.Web/Areas/Admin/Controllers/AddressAttributeController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Web.Areas.Admin.Extensions;
using Nop.Web.Areas.Admin.Models.Common;
using Nop.Core;
using Nop.Core.Domain.Common;
using Nop.Services.Common;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Security;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class AddressAttributeController : BaseAdminController
    {
        #region Fields

        private readonly IAddressAttributeService _addressAttributeService;
        private readonly ILanguageService _languageService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly IPermissionService _permissionService;
        private readonly ICustomerActivityService _customerActivityService;

        #endregion

        #region Ctor

        public AddressAttributeController(IAddressAttributeService addressAttributeService,
            ILanguageService languageService, 
            ILocalizedEntityService localizedEntityService,
            ILocalizationService localizationService,
            IWorkContext workContext,
            IPermissionService permissionService,
            ICustomerActivityService customerActivityService)
        {
            this._addressAttributeService = addressAttributeService;
            this._languageService = languageService;
            this._localizedEntityService = localizedEntityService;
            this._localizationService = localizationService;
            this._workContext = workContext;
            this._permissionService = permissionService;
            this._customerActivityService = customerActivityService;
        }

        #endregion
        
        #region Utilities

        protected virtual void UpdateAttributeLocales(AddressAttribute addressAttribute, AddressAttributeModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(addressAttribute,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }

        protected virtual void UpdateValueLocales(AddressAttributeValue addressAttributeValue, AddressAttributeValueModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(addressAttributeValue,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }

        #endregion

        #region Address attributes

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult ListBlock()
        {
            return PartialView("ListBlock");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //we just redirect a user to the address settings page
             
            //select "address form fields" tab
            SaveSelectedTabName("tab-addressformfields");
            return RedirectToAction("CustomerUser", "Setting");
        }

        [HttpPost]
        public virtual IActionResult List(DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedKendoGridJson();

            var addressAttributes = _addressAttributeService.GetAllAddressAttributes();
            var gridModel = new DataSourceResult
            {
                Data = addressAttributes.Select(x =>
                {
                    var attributeModel = x.ToModel();
                    attributeModel.AttributeControlTypeName = x.AttributeControlType.GetLocalizedEnum(_localizationService, _workContext);
                    return attributeModel;
                }),
                Total = addressAttributes.Count()
            };
            return Json(gridModel);
        }

        //create
        public virtual IActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            var model = new AddressAttributeModel();
            //locales
            AddLocales(_languageService, model.Locales);
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Create(AddressAttributeModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var addressAttribute = model.ToEntity();
                _addressAttributeService.InsertAddressAttribute(addressAttribute);

                //activity log
                _customerActivityService.InsertActivity("AddNewAddressAttribute",
                    string.Format(_localizationService.GetResource("ActivityLog.AddNewAddressAttribute"), addressAttribute.Id), addressAttribute);

                //locales
                UpdateAttributeLocales(addressAttribute, model);

                SuccessNotification(_localizationService.GetResource("Admin.Address.AddressAttributes.Added"));

                if (continueEditing)
                {
                    //selected tab
                    SaveSelectedTabName();

                    return RedirectToAction("Edit", new { id = addressAttribute.Id });
                }
                return RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            return View(model);
        }

        //edit
        public virtual IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            var addressAttribute = _addressAttributeService.GetAddressAttributeById(id);
            if (addressAttribute == null)
                //No address attribute found with the specified id
                return RedirectToAction("List");

            var model = addressAttribute.ToModel();
            //locales
            AddLocales(_languageService, model.Locales, (locale, languageId) =>
            {
                locale.Name = addressAttribute.GetLocalized(x => x.Name, languageId, false, false);
            });
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Edit(AddressAttributeModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            var addressAttribute = _addressAttributeService.GetAddressAttributeById(model.Id);
            if (addressAttribute == null)
                //No address attribute found with the specified id
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                addressAttribute = model.ToEntity(addressAttribute);
                _addressAttributeService.UpdateAddressAttribute(addressAttribute);

                //activity log
                _customerActivityService.InsertActivity("EditAddressAttribute",
                    string.Format(_localizationService.GetResource("ActivityLog.EditAddressAttribute"), addressAttribute.Id), addressAttribute);

                //locales
                UpdateAttributeLocales(addressAttribute, model);

                SuccessNotification(_localizationService.GetResource("Admin.Address.AddressAttributes.Updated"));
                if (continueEditing)
                {
                    //selected tab
                    SaveSelectedTabName();

                    return RedirectToAction("Edit", new {id = addressAttribute.Id});
                }
                return RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            return View(model);
        }

        //delete
        [HttpPost]
        public virtual IActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            var addressAttribute = _addressAttributeService.GetAddressAttributeById(id);
            _addressAttributeService.DeleteAddressAttribute(addressAttribute);

            //activity log
            _customerActivityService.InsertActivity("DeleteAddressAttribute",
                string.Format(_localizationService.GetResource("ActivityLog.DeleteAddressAttribute"), addressAttribute.Id), addressAttribute);

            SuccessNotification(_localizationService.GetResource("Admin.Address.AddressAttributes.Deleted"));
            return RedirectToAction("List");
        }

        #endregion

        #region Address attribute values

        //list
        [HttpPost]
        public virtual IActionResult ValueList(int addressAttributeId, DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedKendoGridJson();

            var values = _addressAttributeService.GetAddressAttributeValues(addressAttributeId);
            var gridModel = new DataSourceResult
            {
                Data = values.Select(x => new AddressAttributeValueModel
                {

Presentation/Nop.Web/Areas/Merchant/Views/AddressAttribute/Create.cshtml
@model AddressAttributeModel
@{
    //page title
    ViewBag.Title = T("Merchant.Address.AddressAttributes.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Customer and user settings");
}

<form asp-controller="AddressAttribute" asp-action="Create" method="post" id="addressattribute-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Merchant.Address.AddressAttributes.AddNew")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Merchant.Address.AddressAttributes.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Merchant.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Merchant.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("MerchantWidget", new { widgetZone = MerchantWidgetZones.AddressAttributeDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

Presentation/Nop.Web/Areas/Merchant/Views/AddressAttribute/Edit.cshtml
@model AddressAttributeModel
@{
    //page title
    ViewBag.Title = T("Merchant.Address.AddressAttributes.EditAttributeDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Customer and user settings");
}

<form asp-controller="AddressAttribute" asp-action="Edit" method="post" id="addressattribute-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Merchant.Address.AddressAttributes.EditAttributeDetails") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Merchant.Address.AddressAttributes.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Merchant.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Merchant.Common.SaveContinue")
            </button>
            <span id="addressattribute-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Merchant.Common.Delete")
            </span>
            @await Component.InvokeAsync("MerchantWidget", new { widgetZone = MerchantWidgetZones.AddressAttributeDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="addressattribute-delete"/>

Presentation/Nop.Web/Areas/Merchant/Views/AddressAttribute/ListBlock.cshtml
<div class="panel panel-default">
    <div class="panel-heading">
        @T("Merchant.Address.AddressAttributes")
    </div>
    <div class="panel-body">
        <p>
            <em>@T("Merchant.Address.AddressAttributes.Description")</em>
        </p>
        <div id="addressattributes-grid"></div>

        <script>
                $(document).ready(function () {
                    $("#addressattributes-grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("List", "AddressAttribute"))",
                                    type: "POST",
                                    dataType: "json",
                                    data: addAntiForgeryToken
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors"
                            },
                            error: function(e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            numeric: false,
                            previousNext: false,
                            info: false,
                            @await Html.PartialAsync("_GridPagerMessages")
                        },
                        editable: {
                            confirmation: "@T("Merchant.Common.DeleteConfirmation")",
                            mode: "inline"
                        },
                        scrollable: false,
                        columns: [{
                            field: "Name",
                            title: "@T("Merchant.Address.AddressAttributes.Fields.Name")",
                            width: 300
                        }, {
                            field: "AttributeControlTypeName",
                            title: "@T("Merchant.Address.AddressAttributes.Fields.AttributeControlType")",
                            width: 200
                        },{
                            field: "IsRequired",
                            title: "@T("Merchant.Address.AddressAttributes.Fields.IsRequired")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '# if(IsRequired) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                        }, {
                            field: "DisplayOrder",
                            title: "@T("Merchant.Address.AddressAttributes.Fields.DisplayOrder")",
                            width: 100
                        }, {
                            field: "Id",
                            title: "@T("Merchant.Common.Edit")",
                            width: 80,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<a class="btn btn-default" href="@Url.Content("~/Merchant/AddressAttribute/Edit/")#=Id#"><i class="fa fa-pencil"></i>@T("Merchant.Common.Edit")</a>'
                        }]
                    });
                });
        </script>
    </div>
    <div class="panel-footer">
        <a asp-action="Create" asp-controller="AddressAttribute" class="btn btn-primary">
            <i class="fa fa-plus-square"></i>
            @T("Merchant.Common.AddNew")
        </a>
    </div>
</div>

Presentation/Nop.Web/Areas/Merchant/Views/AddressAttribute/ValueCreatePopup.cshtml
@model AddressAttributeValueModel
@{
    Layout = "_MerchantPopupLayout";

    //page title
    ViewBag.Title = T("Merchant.Address.AddressAttributes.Values.AddNew").Text;
}
<form asp-controller="AddressAttribute" asp-action="ValueCreatePopup"
      asp-route-addressAttributeId="@Context.Request.Query["addressAttributeId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Merchant.Address.AddressAttributes.Values.AddNew")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Merchant.Common.Save")
            </button>
            @await Component.InvokeAsync("MerchantWidget", new { widgetZone = MerchantWidgetZones.AddressAttributeValueDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateValue", Model)
</form>

Presentation/Nop.Web/Areas/Merchant/Views/AddressAttribute/ValueEditPopup.cshtml
@model AddressAttributeValueModel
@{
    Layout = "_MerchantPopupLayout";

    //page title
    ViewBag.Title = T("Merchant.Address.AddressAttributes.Values.EditValueDetails").Text;
}
<form asp-controller="AddressAttribute" asp-action="ValueEditPopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Merchant.Address.AddressAttributes.Values.EditValueDetails")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Merchant.Common.Save")
            </button>
            @await Component.InvokeAsync("MerchantWidget", new { widgetZone = MerchantWidgetZones.AddressAttributeValueDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateValue", Model)
</form>

Presentation/Nop.Web/Areas/Merchant/Views/AddressAttribute/_CreateOrUpdate.Info.cshtml
@using Nop.Core.Domain.Catalog
@using Nop.Services
@model AddressAttributeModel

<div class="panel-group">
    @await Component.InvokeAsync("MerchantWidget", new { widgetZone = MerchantWidgetZones.AddressAttributeDetailsInfoTop, additionalData = Model })
    <div class="panel panel-default">
        <div class="panel-body">
            @(Html.LocalizedEditor<AddressAttributeModel, AddressAttributeLocalizedModel>("addressattribute-localized",
                  @<div>
                      <div class="form-group">
                          <div class="col-md-3">
                              <nop-label asp-for="@Model.Locales[item].Name" />
                          </div>
                          <div class="col-md-9">
                              <nop-editor asp-for="@Model.Locales[item].Name" />
                              <span asp-validation-for="@Model.Locales[item].Name"></span>
                          </div>
                      </div>
                       <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
                  </div>
                    ,
                  @<div>
                      <div class="form-group">
                          <div class="col-md-3">
                              <nop-label asp-for="Name" />
                          </div>
                          <div class="col-md-9">
                              <nop-editor asp-for="Name" asp-required="true" />
                              <span asp-validation-for="Name"></span>
                          </div>
                      </div>
                  </div>
                  ))

            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="IsRequired" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="IsRequired" />
                    <span asp-validation-for="IsRequired"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="AttributeControlTypeId" />
                </div>
                <div class="col-md-9">
                    @{
                        IEnumerable<SelectListItem> attributeControlTypes = ((AttributeControlType)Model.AttributeControlTypeId)
                            .ToSelectList(valuesToExclude:
                                //these attributes don't support some control types
                                new[] { (int)AttributeControlType.FileUpload, (int)AttributeControlType.Datepicker, (int)AttributeControlType.ColorSquares, (int)AttributeControlType.ImageSquares });
                    }
                    <nop-select asp-for="AttributeControlTypeId" asp-items="@attributeControlTypes"/>
                    <span asp-validation-for="AttributeControlTypeId"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="DisplayOrder" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="DisplayOrder" />
                    <span asp-validation-for="DisplayOrder"></span>
                </div>
            </div>
        </div>
    </div>
    @await Component.InvokeAsync("MerchantWidget", new { widgetZone = MerchantWidgetZones.AddressAttributeDetailsInfoBottom, additionalData = Model })
</div>

Presentation/Nop.Web/Areas/Merchant/Views/AddressAttribute/_CreateOrUpdate.Values.cshtml
@model AddressAttributeModel

<div class="panel-group">
    @await Component.InvokeAsync("MerchantWidget", new { widgetZone = MerchantWidgetZones.AddressAttributeDetailsValuesTop, additionalData = Model })
    <div class="panel panel-default">
        @if (Model.Id > 0)
        {
            /*TODO display the following warning if values are not supported by selected attribute control type
                'Values are not required for this attribute control type'
                */
            <div class="panel-body">
                <div id="addressattributevalues-grid"></div>

                <script>
                    $(document).ready(function () {
                        $("#addressattributevalues-grid").kendoGrid({
                            dataSource: {
                                type: "json",
                                transport: {
                                    read: {
                                        url: "@Html.Raw(Url.Action("ValueList", "AddressAttribute", new { addressAttributeId = Model.Id }))",
                                        type: "POST",
                                        dataType: "json",
                                        data: addAntiForgeryToken
                                    },
                                    destroy: {
                                        url: "@Html.Raw(Url.Action("ValueDelete", "AddressAttribute"))",
                                        type: "POST",
                                        dataType: "json",
                                        data: addAntiForgeryToken
                                    }
                                },
                                schema: {
                                    data: "Data",
                                    total: "Total",
                                    errors: "Errors",
                                    model: {
                                        id: "Id"
                                    }
                                },
                                error: function (e) {
                                    display_kendoui_grid_error(e);
                                    // Cancel the changes
                                    this.cancelChanges();
                                },
                                serverPaging: true,
                                serverFiltering: true,
                                serverSorting: true
                            },
                            pageable: {
                                refresh: true,
                                numeric: false,
                                previousNext: false,
                                info: false,
                                @await Html.PartialAsync("_GridPagerMessages")
                            },
                            editable: {
                                confirmation: "@T("Merchant.Common.DeleteConfirmation")",
                                mode: "inline"
                            },
                            scrollable: false,
                            columns: [{
                                field: "Name",
                                title: "@T("Merchant.Address.AddressAttributes.Values.Fields.Name")"
                            }, {
                                field: "IsPreSelected",
                                title: "@T("Merchant.Address.AddressAttributes.Values.Fields.IsPreSelected")",
                                width: 100,
                                headerAttributes: { style: "text-align:center" },
                                attributes: { style: "text-align:center" },
                                template: '# if(IsPreSelected) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                            }, {
                                field: "DisplayOrder",
                                title: "@T("Merchant.Address.AddressAttributes.Values.Fields.DisplayOrder")",
                                width: 100
                            }, {
                                field: "Id",
                                title: "@T("Merchant.Common.Edit")",
                                width: 100,
                                headerAttributes: { style: "text-align:center" },
                                attributes: { style: "text-align:center" },
                                template: "<button value='@T("Merchant.Common.Edit")' onclick=\"javascript:OpenWindow('@Url.Content("~/Merchant/AddressAttribute/ValueEditPopup/")#=Id#?btnId=btnRefresh&formId=addressattribute-form', 800, 400, true); return false;\" class='btn btn-default'><i class=\"fa fa-pencil\"></i>@T("Merchant.Common.Edit")</button>"
                            }, {
                                command: { name: "destroy", text: "@T("Merchant.Common.Delete")" },
                                title: "@T("Merchant.Common.Delete")",
                                width: 100
                            }]
                        });
                    });
                </script>
            </div>
            <div class="panel-footer">
                <button type="submit" id="btnAddNewValue" onclick="javascript:OpenWindow('@(Url.Action("ValueCreatePopup", "AddressAttribute", new {addressAttributeId = Model.Id, btnId = "btnRefresh", formId = "addressattribute-form"}))', 800, 400, true); return false;" class="btn btn-primary">
                    @T("Merchant.Address.AddressAttributes.Values.AddNew")
                </button>
                <input type="submit" id="btnRefresh" style="display: none" />
                <script>
                    $(document).ready(function () {
                        $('#btnRefresh').click(function () {
                            //refresh grid
                            var grid = $("#addressattributevalues-grid").data('kendoGrid');
                            grid.dataSource.read();

                            //return false to don't reload a page
                            return false;
                        });
                    });
                </script>
            </div>
        }
        else
        {
            <div class="panel-body">
                @T("Merchant.Address.AddressAttributes.Values.SaveBeforeEdit")
            </div>
        }
    </div>
    @await Component.InvokeAsync("MerchantWidget", new { widgetZone = MerchantWidgetZones.AddressAttributeDetailsValuesBottom, additionalData = Model })
</div>

Presentation/Nop.Web/Areas/Merchant/Views/AddressAttribute/_CreateOrUpdate.cshtml
@model AddressAttributeModel
@inject IEventPublisher eventPublisher

<div class="content">
    <div asp-validation-summary="All"></div>
    <input asp-for="Id" type="hidden"/>

    <div class="form-horizontal">
        <nop-tabs id="addressattribute-edit">
            <nop-tab asp-name="tab-info" asp-title="@T("Merchant.Address.AddressAttributes.Info")" asp-default="true">@await Html.PartialAsync("_CreateOrUpdate.Info", Model)</nop-tab>
            <nop-tab asp-name="tab-values" asp-title="@T("Merchant.Address.AddressAttributes.Values")">@await Html.PartialAsync("_CreateOrUpdate.Values", Model)</nop-tab>
        </nop-tabs>
    </div>
</div>

@{
    //custom tabs
    var eventMessage = new MerchantTabStripCreated(this.Html, "addressattribute-edit");
    eventPublisher.Publish(eventMessage);
    foreach (var eventBlock in eventMessage.BlocksToRender)
    {
        @eventBlock
    }
}